-- ====================================================================
-- POLARIS POLAR RESEARCH STATION ENERGY MANAGEMENT SYSTEM
-- Supabase PostgreSQL Schema Migration (SIH Problem Statement 26061)
-- ====================================================================

-- 1. High-Precision Time-Series Telemetry Table
CREATE TABLE IF NOT EXISTS public.telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step INT,
    timestamp TEXT,
    solar_power_kw DOUBLE PRECISION DEFAULT 0.0,
    wind_power_kw DOUBLE PRECISION DEFAULT 0.0,
    total_generation_kw DOUBLE PRECISION DEFAULT 0.0,
    total_station_load_kw DOUBLE PRECISION DEFAULT 0.0,
    critical_load_kw DOUBLE PRECISION DEFAULT 0.0,
    flexible_load_kw DOUBLE PRECISION DEFAULT 0.0,
    battery_soc_pct DOUBLE PRECISION DEFAULT 0.0,
    battery_power_kw DOUBLE PRECISION DEFAULT 0.0,
    battery_temperature_c DOUBLE PRECISION DEFAULT 0.0,
    generator_power_kw DOUBLE PRECISION DEFAULT 0.0,
    power_balance_kw DOUBLE PRECISION DEFAULT 0.0,
    renewable_percentage DOUBLE PRECISION DEFAULT 0.0,
    temperature_c DOUBLE PRECISION DEFAULT 0.0,
    wind_speed_m_s DOUBLE PRECISION DEFAULT 0.0,
    cloud_cover DOUBLE PRECISION DEFAULT 0.0,
    weather_condition TEXT,
    ai_action INT DEFAULT 0,
    ai_action_name TEXT,
    ai_reward DOUBLE PRECISION DEFAULT 0.0,
    energy_deficit_kw DOUBLE PRECISION DEFAULT 0.0,
    energy_surplus_kw DOUBLE PRECISION DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_telemetry_id_desc ON public.telemetry (id DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_step ON public.telemetry (step);
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp ON public.telemetry (timestamp);

-- 2. Dynamic Station Alerts Table
CREATE TABLE IF NOT EXISTS public.alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_code TEXT,
    severity TEXT DEFAULT 'info',
    title TEXT,
    message TEXT,
    timestamp TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_id_desc ON public.alerts (id DESC);

-- 3. AI Decisions & Policy Rationale Log
CREATE TABLE IF NOT EXISTS public.ai_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step INT,
    timestamp TEXT,
    action INT,
    action_name TEXT,
    reason TEXT,
    reward DOUBLE PRECISION DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_decisions_id_desc ON public.ai_decisions (id DESC);

-- 4. Continuous AI Training History
CREATE TABLE IF NOT EXISTS public.training_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT,
    episode INT,
    current_reward DOUBLE PRECISION DEFAULT 0.0,
    average_reward DOUBLE PRECISION DEFAULT 0.0,
    best_reward DOUBLE PRECISION DEFAULT 0.0,
    progress_pct DOUBLE PRECISION DEFAULT 0.0,
    critical_availability_pct DOUBLE PRECISION DEFAULT 100.0,
    renewable_utilization_pct DOUBLE PRECISION DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_training_history_id_desc ON public.training_history (id DESC);

-- 5. IoT Sensor Readings (from team_modules)
CREATE TABLE IF NOT EXISTS public.sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT,
    temperature_c DOUBLE PRECISION,
    humidity_pct DOUBLE PRECISION,
    wind_speed_mps DOUBLE PRECISION,
    wind_direction_deg DOUBLE PRECISION,
    solar_irradiance_wm2 DOUBLE PRECISION,
    solar_status TEXT,
    wind_status TEXT,
    solar_generation_kw DOUBLE PRECISION,
    wind_generation_kw DOUBLE PRECISION,
    energy_demand_kw DOUBLE PRECISION,
    battery_soc_pct DOUBLE PRECISION,
    generator_status TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;

-- Grant Read & Insert Permissions for Anon/Publishable API Key
CREATE POLICY "Allow public read telemetry" ON public.telemetry FOR SELECT USING (true);
CREATE POLICY "Allow public insert telemetry" ON public.telemetry FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read alerts" ON public.alerts FOR SELECT USING (true);
CREATE POLICY "Allow public insert alerts" ON public.alerts FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read ai_decisions" ON public.ai_decisions FOR SELECT USING (true);
CREATE POLICY "Allow public insert ai_decisions" ON public.ai_decisions FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read training_history" ON public.training_history FOR SELECT USING (true);
CREATE POLICY "Allow public insert training_history" ON public.training_history FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read sensor_readings" ON public.sensor_readings FOR SELECT USING (true);
CREATE POLICY "Allow public insert sensor_readings" ON public.sensor_readings FOR INSERT WITH CHECK (true);
